FROM skpr/base:1.x

ENV PATH "$PATH:/data/bin"

WORKDIR /data

RUN apk --update --no-cache add \
      php7-apcu \
      php7-bcmath \
      php7-ctype \
      php7-curl \
      php7-dom \
      php7-ftp \
      php7-gd \
      php7-iconv \
      php7-json \
      php7-mbstring \
      php7-mcrypt \
      php7-memcached \
      php7-opcache \
      php7-openssl \
      php7-pcntl \
      php7-pdo \
      php7-pdo_mysql \
      php7-pdo_sqlite \
      php7-phar \
      php7-posix \
      php7-session \
      php7-simplexml \
      php7-soap \
      php7-sqlite3 \
      php7-tokenizer \
      php7-xml \
      php7-xmlreader \
      php7-xmlwriter \
      php7-zip \
      pngquant \
      jpegoptim \
      mysql-client \
      optipng
