version: 2

build: &build
  docker:
    - image: previousnext/container-builder:latest
  steps:
    - setup_remote_docker
    - checkout
    - run:
        name: Build, Test and Release
        command: |
          cd $DIR
          make build
          if [ "$CIRCLE_BRANCH" == "master" ]; then
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            make push
          fi

jobs:
  base:
    <<: *build
    environment:
      - DIR: base
  node:
    <<: *build
    environment:
      - DIR: node
  nginx:
    <<: *build
    environment:
      - DIR: nginx
  php:
    <<: *build
    environment:
      - DIR: php
  solr:
    <<: *build
    environment:
      - DIR: solr
  kubebuilder:
    <<: *build
    environment:
      - DIR: kubebuilder

workflows:
  version: 2
  build:
    jobs:
      - base
      - node
      - nginx
      - php
      - solr
      - kubebuilder
  nightly:
    jobs:
      - base
      - node
      - nginx
      - php
      - solr
      - kubebuilder
    triggers:
      - schedule:
          # Scheduled build for 2am AEST nightly.
          cron: "0 15 * * *"
          filters:
            branches:
              only:
                - master
