version: 2.1

dirs: &dirs
  - clamav
  - kubebuilder
  - nginx
  - mysql
  - rsync

jobs:
  build:
    docker:
      - image: previousnext/container-builder:latest
    parameters:
      dir:
        type: string
        default: ""
    steps:
      - setup_remote_docker:
          version: "20.10.11"
      - checkout
      - run:
          name: "Build: Base Image"
          command: |
            cd base
            make build
      - run:
          name: Build, Test and Release
          command: |
            cd << parameters.dir >>
            make build
            if [ "$CIRCLE_BRANCH" == "master" ]; then
              docker login -u $DOCKER_USER -p $DOCKER_PASS
              make push
            fi
